### ISSUE TITLE
Compile Problems with tabs in Arduino IDE

### ISSUE THREAD

**Issue by jhnwmr** [eta-systems/MAX7313-Arduino#4]
Hello,
The library is often used by me and I would like to thank you very much for maintaining it!
In my latest project I want to increase the clarity and use tabs in IDE.
So in the main INO the tab is added via #include "file.h".
In other projects I have done this several times.
However, errors occur when copmpiling with this library.
I don't have a complete script yet and hope that the excerpts describe my problem well.

Now the question is am I doing something wrong or is the cause of this error coming from the library?

**Main INO:**
```
#include <Wire.h>
#include "MAX7313.h"
#include "shutter.h"

const int16_t ADDR = 0x64;
MAX7313 expander(ADDR);

void setup() {
  Serial.begin(115200);
  Wire.begin();
  expander.begin();
  expander.pinMode(0, OUTPUT);
  expander.pinMode(10, INPUT);
  expander.analogWrite(0, 15);
}

void loop() {
  shutter();
}
```
**Shutter.h:**
```
void shutter() {
  unsigned long currentMillis = millis();

  if (expander.digitalRead(JAL_UP_BUTTON) == LOW && expander.digitalRead(JAL_DOWN_BUTTON) == HIGH && down_int == 0) {
      //  Abridged

```

**Error:**

```
Compilation error: 'expander' was not declared in this scope
```

**Comment by mnemocron** [comment]
Hi, I am happy that the library is useful to somebody out there.

Since you didn't post a reproducible file, I am going to point to a few things first from your post:

- it is unusual to include code (other than definitions) in a header `.h` file. The `void shutter()` implementation should go into a separate `shutter.cpp` file.
- you instantiate (define) the `expander` object in your main `.ino` file. All other files do not know about this instance. You could use the `extern` statement to reference it again.

So for example

### main.ino
```c++
#include <Wire.h>
#include "MAX7313.h"
#include "shutter.h"

const int16_t ADDR = 0x64;
MAX7313 expander(ADDR);

void setup() {
  Serial.begin(115200);
  Wire.begin();
  expander.begin();
  expander.pinMode(0, OUTPUT);
  expander.pinMode(10, INPUT);
  expander.analogWrite(0, 15);
}

void loop() {
  shutter();
}
```

### shutter.h
```c++
#include "MAX7313.h"

void shutter();
```

### shutter.cpp
```c++
#include "shutter.h"
#include "MAX7313.h"

// define the 'expander' object and tell the compiler that the object is somewhere
// outside of this file. in this case in main.ino
extern MAX7313 expander;

void shutter() {
  // do something with expander here
  expander.digitalRead(JAL_DOWN_BUTTON);
}
```


Tell me if that fixes your problem.

**Comment by jhnwmr** [comment]
Thank you for your explanation. That helped me a lot.
